local BlizardTypes =
{
	-- defined: AnchorBinding
	-- defined: uiRect

	-- UI_shared.xsd
	-- <xs:simpleType name="FRAMEPOINT">, SetPoint
	{ Name = "FramePoint", Type = "string", Values = {"TOPLEFT", "TOPRIGHT", "BOTTOMLEFT", "BOTTOMRIGHT", "TOP", "BOTTOM", "LEFT", "RIGHT", "CENTER"} },
	-- <xs:simpleType name="FRAMESTRATA">, SetFrameStrata
	-- { Name = "FrameStrata", Type = "string", Values = {"PARENT", "BACKGROUND", "LOW", "MEDIUM", "HIGH", "DIALOG", "FULLSCREEN", "FULLSCREEN_DIALOG", "TOOLTIP", "BLIZZARD"} },
	{ Name = "FrameStrata", Type = "string", Link = "Frame_Strata" },
	-- <xs:simpleType name="DRAWLAYER">, SetDrawLayer
	-- { Name = "DrawLayer", Type = "string", Values = {"BACKGROUND", "BORDER", "ARTWORK", "OVERLAY", "HIGHLIGHT"} },
	{ Name = "DrawLayer", Type = "string", Link = "Layer" },
	-- <xs:simpleType name="ANIMCURVETYPE">, SetCurveType
	{ Name = "CurveType", Type = "string", Values = {"NONE", "SMOOTH"} },
	-- <xs:simpleType name="JUSTIFYVTYPE">, SetJustifyV
	-- <xs:simpleType name="JUSTIFYHTYPE">, SetJustifyH
	{ Name = "TBFStyleFlags", Type = "string", Values = {"CENTER", "LEFT", "RIGHT", "TOP", "BOTTOM"} },
	-- SetFont
	{ Name = "TBFFlags", Type = "string", Values = {"OUTLINE", "THICK", "MONOCHROME"} },
	-- <xs:simpleType name="ORIENTATION"> SetOrientation
	{ Name = "Orientation", Type = "string", Values = {"HORIZONTAL", "VERTICAL"} },
	-- <xs:simpleType name="ALPHAMODE">, SetBlendMode
	-- { Name = "BlendMode", Type = "string", Values = {"DISABLE", "BLEND", "ALPHAKEY", "ADD", "MOD"} },
	{ Name = "BlendMode", Type = "string", Link = "UITYPE_AlphaMode"  },
	-- <xs:simpleType name="INSERTMODE">, SetInsertMode, (number or string?, see framexml usage)
	{ Name = "InsertMode", Type = "string", Values = {"TOP", "BOTTOM"} },
	-- <xs:simpleType name="ANIMSMOOTHTYPE">
	{ Name = "SmoothingType", Type = "string", Values = {"NONE", "IN", "OUT", "IN_OUT", "OUT_IN"} },
	-- <xs:simpleType name="ANIMLOOPTYPE">
	{ Name = "LoopType", Type = "string", Values = {"NONE", "REPEAT", "BOUNCE"} },

	{ Name = "StatusBarFillStyle", Type = "string", Values = {"STANDARD", "STANDARD_NO_RANGE_FILL", "CENTER", "REVERSE"} },
	{ Name = "SimpleButtonStateToken", Type = "string", Values = {"NORMAL", "PUSHED"} },
	{ Name = "UnitToken", Type = "string", Values = {"player", "target", "focus", "mouseover" , "pet" , "vehicle" , "npc" , "questnpc" , "none" , "party1" , "raid1" , "nameplate1" , "arena1" , "boss1"}, Link = "UnitId" },
	-- SetAtlas, SetTexture
	{ Name = "FilterMode", Type = "string", Values = {"LINEAR", "TRILINEAR", "NEAREST"} },

	-- basic types
	{ Name = "cstring", Type = "string", Common = true },
	{ Name = "luaIndex", Type = "number", Common = true },
	{ Name = "luaFunction", Type = "function", Common = true },
	-- BigInteger in RecruitingClubInfo.lastUpdatedTime (unix time)
	  -- /dump C_ClubFinder.GetRecruitingClubInfoFromFinderGUID(C_ClubFinder.ReturnMatchingGuildList()[1].clubFinderGUID)
	{ Name = "BigInteger", Type = "number" },
	{ Name = "BigUInteger", Type = "number" },
	{ Name = "normalizedValue", Type = "number" }, -- [0.0 - 1.0]
	{ Name = "SingleColorValue", Type = "number", Common = true }, -- [0.0 - 1.0], used mainly for alpha
	{ Name = "BagIndex", Type = "number" }, -- already exists as an enum
	-- multiple types
	{ Name = "uiAddon", Type = "number|string" },
	{ Name = "ItemInfo", Type = "number|string" }, -- item id, link, name
	-- IDs
	{ Name = "fileID", Type = "number", Link = "FileDataID" },
	{ Name = "CalendarEventID", Type = "number" }, -- (used to be a string according to previous docs?)
	{ Name = "InventorySlots", Type = "number", Link = "InventorySlotId" },
	-- GUIDs
	{ Name = "WOWGUID", Type = "string", Link = "GUID" },
	{ Name = "ClubId", Type = "string" },
	{ Name = "ClubStreamId", Type = "string" },
	{ Name = "ClubInvitationId", Type = "string" },
	{ Name = "GarrisonFollower", Type = "string" },
	{ Name = "RecruitAcceptanceID", Type = "string" },
	-- base units
	{ Name = "size", Type = "number" }, -- only used for Texture:GetNumMaskTextures
	{ Name = "time_t", Type = "number" }, -- time in seconds
	{ Name = "uiUnit", Type = "number" }, -- user interface units
	{ Name = "uiFontHeight", Type = "number" }, -- font height
	{ Name = "WOWMONEY", Type = "number", Description = "Amount in copper" }, -- money in copper
	-- assets
	{ Name = "FileAsset", Type = "string" }, -- texture path
	{ Name = "ModelAsset", Type = "string" },
	{ Name = "TextureAsset", Type = "string|Texture" },
	{ Name = "textureAtlas", Type = "string", Link = "AtlasID" }, -- texture atlas
	{ Name = "textureKit", Type = "string", Link = "dbc:UiTextureKit" }, -- (what happened to textureKitID as a number?)
	-- kstrings
	{ Name = "kstringLfgListApplicant", Type = "string" },
	{ Name = "kstringLfgListChat", Type = "string" },
	{ Name = "kstringClubMessage", Type = "string" },
	{ Name = "kstringLfgListSearch", Type = "string" },

	{ Name = "HTMLTextType", Type = "string" },
	{ Name = "NotificationDbId", Type = "string" },
	-- WeeklyRewardItemDBID in WeeklyRewardActivityRewardInfo
	  -- /dump C_WeeklyRewards.GetActivities()[1].rewards
	{ Name = "WeeklyRewardItemDBID", Type = "string" },

	-- widgets
	-- defined: ScriptObject
	{ Name = "CScriptObject", Type = "FrameScriptObject", Replace = true },
	{ Name = "ModelSceneFrame", Type = "ModelScene", Replace = true },
	{ Name = "ModelSceneFrameActor", Type = "ModelSceneActor", Replace = true },
	-- { Name = "ScriptRegion", Type = "ScriptRegion", Replace = true },
	{ Name = "SimpleAnim", Type = "Animation", Replace = true },
	{ Name = "SimpleAnimGroup", Type = "AnimationGroup", Replace = true },
	{ Name = "SimpleControlPoint", Type = "ControlPoint", Replace = true },
	{ Name = "SimpleFont", Type = "Font", Replace = true, },
	{ Name = "SimpleFontString", Type = "FontString", Replace = true },
	-- { Name = "FontString", Type = "FontString", Link = "UIOBJECT_FontString" },
	{ Name = "SimpleFrame", Type = "Frame", Replace = true },
	{ Name = "SimpleLine", Type = "Line", Replace = true },
	{ Name = "SimpleMaskTexture", Type = "MaskTexture", Replace = true },
	{ Name = "SimplePathAnim", Type = "Path", Replace = true },
	{ Name = "SimpleTexture", Type = "Texture", Replace = true },
	-- frame widgets
	{ Name = "ChatBubbleFrame", Type = "Frame" },
	{ Name = "NamePlateFrame", Type = "Frame", Mixin = "NamePlateBaseMixin" },

	-- mixins
	{ Name = "vector2", Type = "Mixin", Mixin = "Vector2DMixin" },
	{ Name = "vector3", Type = "Mixin", Mixin = "Vector3DMixin" },
	{ Name = "colorRGB", Type = "Mixin", Mixin = "ColorMixin" },
	{ Name = "colorRGBA", Type = "Mixin", Mixin = "ColorMixin" },
	{ Name = "ItemLocation", Type = "Mixin", Mixin = "ItemLocationMixin" },
	{ Name = "EmptiableItemLocation", Type = "Mixin", Mixin = "ItemLocationMixin" },
	{ Name = "AzeriteItemLocation", Type = "Mixin", Mixin = "ItemLocationMixin" },
	{ Name = "AzeriteEmpoweredItemLocation", Type = "Mixin", Mixin = "ItemLocationMixin" },
	{ Name = "PlayerLocation", Type = "Mixin", Mixin = "PlayerLocationMixin" },
	{ Name = "TransmogLocation", Type = "Mixin", Mixin = "TransmogLocationMixin" },
	{ Name = "ItemTransmogInfo", Type = "Mixin", Mixin = "ItemTransmogInfoMixin" },
	{ Name = "TransmogPendingInfo", Type = "Mixin", Mixin = "TransmogPendingInfoMixin" },
	{ Name = "ReportInfo", Type = "Mixin", Mixin = "ReportInfoMixin" },
}

local data = {
	custom = {
		-- AddonMessageParams = true,
		-- AnchorBinding = true,
		-- FramePoint = "string",
		-- uiRect = true,
	},
	enum = {
		["Enum.ItemQuality"] = true,
		["Enum.CraftingOrderResult"] = true,
		["Enum.RafLinkType"] = true,
		["Enum.InventoryType"] = true,
	},
	widget = {
		-- ScriptRegion = true,
		Font = true,
		Texture = true,
		Frame = true,
		FontString = true,
		Line = true,
		AnimationGroup = true,
		MaskTexture = true,
	},
	structure = {
		AlliedRaceInfo = true,
		AlliedRaceRacialAbility = true,
		AnimaDiversionCostInfo = true,
		AnimaDiversionFrameInfo = true,
		AnimaDiversionNodeInfo = true,
		AppearanceSourceInfo = true,
		ArdenwealdGardenData = true,
		AreaPOIInfo = true,
		ArtifactAppearanceInfo = true,
		ArtifactAppearanceSetInfo = true,
		ArtifactArtInfo = true,
		ArtifactInfo = true,
		ArtifactMetaPowerInfo = true,
		ArtifactPowerInfo = true,
		ArtifactRelicInfo = true,
		AtlasInfo = true,
		AuctionHouseBrowseQuery = true,
		AuctionHouseFilterGroup = true,
		AuctionHouseItemClassFilter = true,
		AuctionHouseSortType = true,
		AuctionInfo = true,
		AutoCombatDamageClassString = true,
		AutoCombatResult = true,
		AutoCombatSpellInfo = true,
		AutoCombatTroopInfo = true,
		AutoMissionCombatEventInfo = true,
		AutoMissionEnvironmentEffect = true,
		AutoMissionEvent = true,
		AutoMissionRound = true,
		AutoMissionTargetingInfo = true,
		AzeriteEmpoweredItemPowerInfo = true,
		AzeriteEmpoweredItemPowerText = true,
		AzeriteEmpoweredItemTierInfo = true,
		AzeriteEssenceInfo = true,
		AzeriteMilestoneInfo = true,
		AzeriteSpecInfo = true,
		BNetAccountInfo = true,
		BNetGameAccountInfo = true,
		BackpackCurrencyInfo = true,
		BarberShopCharacterData = true,
		BarberShopRaceData = true,
		BattlefieldCurrencyReward = true,
		BattlefieldItemReward = true,
		BattlefieldRewards = true,
		BattlefieldVehicleInfo = true,
		BattlemasterListInfo = true,
		BestDungeonScoreMapInfo = true,
		BidInfo = true,
		BountyInfo = true,
		BrowseResultInfo = true,
		BulletTextListWidgetVisualizationInfo = true,
		CalendarDayEvent = true,
		CalendarEventIndexInfo = true,
		CalendarEventInfo = true,
		CalendarEventInviteInfo = true,
		CalendarEventStatusOption = true,
		CalendarEventTextureInfo = true,
		CalendarEventTypeDisplayInfo = true,
		CalendarGuildEventInfo = true,
		CalendarGuildFilterInfo = true,
		CalendarHolidayInfo = true,
		CalendarMonthInfo = true,
		CalendarRaidInfo = true,
		CalendarTime = true,
		CampaignChapterInfo = true,
		CampaignFailureReason = true,
		CampaignInfo = true,
		CaptureBarWidgetVisualizationInfo = true,
		CaptureZoneVisualizationInfo = true,
		ChallengeModeCompletionMemberInfo = true,
		ChallengeModeGuildAttemptMember = true,
		ChallengeModeGuildTopAttempt = true,
		CharCustomizationCategory = true,
		CharCustomizationChoice = true,
		CharCustomizationOption = true,
		CharacterAlternateFormData = true,
		ChatChannelInfo = true,
		ChromieTimeExpansionInfo = true,
		ClassInfo = true,
		ClickBindingInfo = true,
		ClubFinderApplicantInfo = true,
		ClubInfo = true,
		ClubInvitationCandidateInfo = true,
		ClubInvitationInfo = true,
		ClubLimits = true,
		ClubMemberInfo = true,
		ClubMessageIdentifier = true,
		ClubMessageInfo = true,
		ClubMessageRange = true,
		ClubPrivilegeInfo = true,
		ClubRoleInfo = true,
		ClubSelfInvitationInfo = true,
		ClubSettingsInfo = true,
		ClubStreamInfo = true,
		ClubStreamNotificationSetting = true,
		ClubTicketInfo = true,
		CommentatorHistory = true,
		CommentatorOverrideNameEntry = true,
		CommentatorPlayerData = true,
		CommentatorSeries = true,
		CommentatorSeriesTeam = true,
		CommentatorTeamDirectoryEntry = true,
		CommentatorUnitData = true,
		CommoditySearchResultInfo = true,
		ConduitCollectionData = true,
		ConquestWeeklyProgress = true,
		ConsoleCommandInfo = true,
		ContainerItemInfo = true,
		ContributionAppearance = true,
		ContributionMapInfo = true,
		ConversionCurrencyCost = true,
		CorruptionEffectInfo = true,
		CovenantAbilityInfo = true,
		CovenantData = true,
		CovenantFeatureInfo = true,
		CovenantPreviewInfo = true,
		CovenantSanctumFeatureInfo = true,
		CovenantSanctumRenownLevelInfo = true,
		CovenantSanctumRenownRewardInfo = true,
		CovenantSoulbindInfo = true,
		CraftingCurrencyResultData = true,
		CraftingItemResultData = true,
		CraftingItemSlotModification = true,
		CraftingOperationBonusStatInfo = true,
		CraftingOperationInfo = true,
		CraftingOrderBucketInfo = true,
		CraftingOrderClaimsRemainingInfo = true,
		CraftingOrderCustomerCategory = true,
		CraftingOrderCustomerCategoryFilters = true,
		CraftingOrderCustomerOptionInfo = true,
		CraftingOrderCustomerSearchParams = true,
		CraftingOrderCustomerSearchResults = true,
		CraftingOrderInfo = true,
		CraftingOrderMailInfo = true,
		CraftingOrderReagentInfo = true,
		CraftingOrderRequestInfo = true,
		CraftingOrderRequestMyOrdersInfo = true,
		CraftingOrderSortInfo = true,
		CraftingReagent = true,
		CraftingReagentInfo = true,
		CraftingReagentSlotInfo = true,
		CraftingReagentSlotSchematic = true,
		CraftingRecipeOutputInfo = true,
		CraftingRecipeRequirement = true,
		CraftingRecipeSchematic = true,
		CraftingRecipeSkillLineInfo = true,
		CraftingResourceReturnInfo = true,
		CraftingTargetItem = true,
		CurrencyCost = true,
		CurrencyDisplayInfo = true,
		CurrencyInfo = true,
		DBColorExport = true,
		DeadlyDebuffInfo = true,
		DigSiteMapInfo = true,
		DiscreteProgressStepsVisualizationInfo = true,
		DoubleIconAndTextWidgetVisualizationInfo = true,
		DoubleStateIconRowVisualizationInfo = true,
		DoubleStatusBarWidgetVisualizationInfo = true,
		DungeonEntranceMapInfo = true,
		EditModeAnchorInfo = true,
		EditModeLayoutInfo = true,
		EditModeLayouts = true,
		EditModeSettingInfo = true,
		EditModeSystemInfo = true,
		EncounterJournalItemInfo = true,
		EncounterJournalMapEncounterInfo = true,
		EncounterJournalSectionInfo = true,
		EventToastInfo = true,
		ExpansionDisplayInfo = true,
		ExpansionDisplayInfoFeature = true,
		FactionInfo = true,
		FillUpFramesWidgetVisualizationInfo = true,
		FogOfWarInfo = true,
		FollowerAutoCombatStatsInfo = true,
		FollowerDisplayID = true,
		FollowerMissionCompleteInfo = true,
		FriendInfo = true,
		FriendshipReputationInfo = true,
		FriendshipReputationRankInfo = true,
		GamePadAxisConfig = true,
		GamePadConfig = true,
		GamePadConfigID = true,
		GamePadMappedState = true,
		GamePadRawAxisMapping = true,
		GamePadRawButtonMapping = true,
		GamePadRawState = true,
		GamePadStick = true,
		GamePadStickConfig = true,
		GarrisonAbilityCounterInfo = true,
		GarrisonAbilityEffect = true,
		GarrisonAbilityInfo = true,
		GarrisonEnemyEncounterInfo = true,
		GarrisonFollowerAbilityInfo = true,
		GarrisonFollowerDeathInfo = true,
		GarrisonMechanicInfo = true,
		GarrisonPlotInstanceMapInfo = true,
		GarrisonTalentCurrencyCostInfo = true,
		GarrisonTalentInfo = true,
		GarrisonTalentSocketInfo = true,
		GarrisonTalentTreeInfo = true,
		GatheringOperationBonusStatInfo = true,
		GatheringOperationInfo = true,
		GenericWidgetDisplayFrameInfo = true,
		GossipOptionRewardInfo = true,
		GossipOptionUIInfo = true,
		GossipPoiInfo = true,
		GossipQuestUIInfo = true,
		GraveyardMapInfo = true,
		GroupFinderActivityInfo = true,
		GuildNewsInfo = true,
		GuildTabardInfo = true,
		GxAdapterInfoDetails = true,
		HTMLContentNode = true,
		HonorRewardInfo = true,
		HorizontalCurrenciesWidgetVisualizationInfo = true,
		IconAndTextWidgetVisualizationInfo = true,
		IconTextAndBackgroundWidgetVisualizationInfo = true,
		IconTextAndCurrenciesWidgetVisualizationInfo = true,
		ImportLoadoutEntryInfo = true,
		InspectPVPData = true,
		InvasionMapInfo = true,
		InventorySlots = true,
		IslandsQueueDifficultyInfo = true,
		ItemInteractionChargeInfo = true,
		ItemInteractionFrameInfo = true,
		ItemKey = true,
		ItemKeyInfo = true,
		ItemPurchaseCurrency = true,
		ItemPurchaseInfo = true,
		ItemPurchaseItem = true,
		ItemQuestInfo = true,
		ItemSearchResultInfo = true,
		ItemUpgradeCurrencyCost = true,
		ItemUpgradeItemInfo = true,
		ItemUpgradeLevelInfo = true,
		ItemUpgradeStat = true,
		LFGDungeonInfo = true,
		LFGLockInfo = true,
		LevelUpBattlegroundInfo = true,
		LfgApplicantData = true,
		LfgCategoryData = true,
		LfgEntryData = true,
		LfgSearchResultData = true,
		LootJournalItemInfo = true,
		LootJournalItemSetInfo = true,
		LoreTextEntry = true,
		LossOfControlData = true,
		MajorFactionData = true,
		MajorFactionFeatureAbilityInfo = true,
		MajorFactionRenownLevelInfo = true,
		MajorFactionRenownRewardInfo = true,
		MapBannerInfo = true,
		MapLinkInfo = true,
		MapSeasonBestInfo = true,
		MapTaxiNodeInfo = true,
		MatchPVPStatColumn = true,
		MinimapScriptTrackingFilter = true,
		MinimapScriptTrackingInfo = true,
		MissionDeploymentInfo = true,
		MissionEncounterIconInfo = true,
		ModelLight = true,
		ModifiedInstanceInfo = true,
		MountCreatureDisplayInfo = true,
		MountInfo = true,
		MountInfoExtra = true,
		MythicPlusAffixScoreInfo = true,
		MythicPlusDate = true,
		MythicPlusKeystoneAffix = true,
		MythicPlusMember = true,
		MythicPlusRatingLinkInfo = true,
		MythicPlusRatingMapSummary = true,
		MythicPlusRatingSummary = true,
		MythicPlusRunInfo = true,
		NameOverrideEntry = true,
		NewCraftingOrderInfo = true,
		OwnedAuctionInfo = true,
		PVPPersonalRatedInfo = true,
		PVPPostMatchCurrencyReward = true,
		PVPPostMatchItemReward = true,
		PVPScoreInfo = true,
		PVPStatInfo = true,
		PVPTeamInfo = true,
		PartyPoseInfo = true,
		PetAbilityLevelInfo = true,
		PetJournalPetInfo = true,
		PetTamerMapInfo = true,
		PlayerChoiceInfo = true,
		PlayerChoiceOptionButtonInfo = true,
		PlayerChoiceOptionInfo = true,
		PlayerChoiceOptionRewardInfo = true,
		PlayerChoiceRewardCurrencyInfo = true,
		PlayerChoiceRewardItemInfo = true,
		PlayerChoiceRewardReputationInfo = true,
		ProfTabInfo = true,
		ProfessionInfo = true,
		PvpBrawlInfo = true,
		PvpRatingInfo = true,
		PvpReadyCheckInfo = true,
		PvpRoleQueueInfo = true,
		PvpScalingData = true,
		PvpTalentInfo = true,
		PvpTalentSlotInfo = true,
		PvpTierInfo = true,
		QuestInfo = true,
		QuestLineInfo = true,
		QuestObjectiveInfo = true,
		QuestOnMapInfo = true,
		QuestReputationRewardInfo = true,
		QuestSessionPlayerDetails = true,
		QuestTagInfo = true,
		QuestTheme = true,
		QueueSpecificInfo = true,
		RaceInfo = true,
		RafAppearanceInfo = true,
		RafAppearanceSetInfo = true,
		RafIllusionInfo = true,
		RafInfo = true,
		RafMountInfo = true,
		RafPetInfo = true,
		RafRecruit = true,
		RafRecruitActivity = true,
		RafRecruitmentinfo = true,
		RafReward = true,
		RafSystemInfo = true,
		RafTitleInfo = true,
		RandomBGInfo = true,
		RatedSoloShuffleSpecStats = true,
		RecruitingClubInfo = true,
		RegularReagentInfo = true,
		ReplicateItemInfo = true,
		RuneforgeItemPreviewInfo = true,
		RuneforgeLegendaryComponentInfo = true,
		RuneforgeLegendaryCraftDescription = true,
		RuneforgePower = true,
		ScenarioHeaderCurrenciesAndBackgroundWidgetVisualizationInfo = true,
		ScenarioHeaderTimerWidgetVisualizationInfo = true,
		ScenarioInformation = true,
		ScenarioStepInfo = true,
		ScenarioStepSpellInfo = true,
		ScriptObject = true,
		ScriptedAnimationEffect = true,
		SelfResurrectOption = true,
		SocialQueueConfig = true,
		SocialQueueGroupInfo = true,
		SocialQueueGroupQueueInfo = true,
		SocialQueuePlayerInfo = true,
		SoulbindConduitData = true,
		SoulbindData = true,
		SoulbindModelSceneData = true,
		SoulbindNode = true,
		SoulbindTree = true,
		SpacerVisualizationInfo = true,
		SpecPerkInfo = true,
		SpecializationCurrencyInfo = true,
		SpecializationTabInfo = true,
		SpellDisplayVisualizationInfo = true,
		SpellInfo = true,
		SplashScreenInfo = true,
		StackedResourceTrackerWidgetVisualizationInfo = true,
		StatusBarWidgetVisualizationInfo = true,
		TaskPOIData = true,
		TaxiNodeInfo = true,
		TextColumnRowEntryInfo = true,
		TextColumnRowVisualizationInfo = true,
		TextWithStateWidgetVisualizationInfo = true,
		TextWithSubtextWidgetVisualizationInfo = true,
		TextureAndTextEntryInfo = true,
		TextureAndTextRowVisualizationInfo = true,
		TextureAndTextVisualizationInfo = true,
		TextureWithAnimationVisualizationInfo = true,
		TooltipComparisonLine = true,
		TooltipData = true,
		TooltipDataArg = true,
		TooltipDataLine = true,
		TooltipItemComparisonInfo = true,
		TradeSkillRecipeInfo = true,
		TraitCondInfo = true,
		TraitConfigInfo = true,
		TraitCurrencyCost = true,
		TraitDefinitionInfo = true,
		TraitEntryInfo = true,
		TraitEntryRankInfo = true,
		TraitGateInfo = true,
		TraitNodeInfo = true,
		TraitNodeInfoPartial = true,
		TraitOutEdgeInfo = true,
		TraitTreeInfo = true,
		TransmogAppearanceInfoBySourceData = true,
		TransmogAppearanceJournalEncounterInfo = true,
		TransmogAppearanceSourceInfoData = true,
		TransmogApplyWarningInfo = true,
		TransmogCategoryAppearanceInfo = true,
		TransmogCategoryInfo = true,
		TransmogIllusionInfo = true,
		TransmogOutfitInfo = true,
		TransmogSetInfo = true,
		TransmogSetPrimaryAppearanceInfo = true,
		TransmogSlotInfo = true,
		TransmogSlotVisualInfo = true,
		TreeCurrencyInfo = true,
		UIModelSceneActorDisplayInfo = true,
		UIModelSceneActorInfo = true,
		UIModelSceneCameraInfo = true,
		UIWidgetCurrencyInfo = true,
		UIWidgetInfo = true,
		UIWidgetSetInfo = true,
		UIWidgetSpellInfo = true,
		UIWidgetStateIconInfo = true,
		UIWidgetTextTooltipPair = true,
		UiMapDetails = true,
		UiMapExplorationHitRect = true,
		UiMapExplorationInfo = true,
		UiMapGroupMemberInfo = true,
		UiMapHighlightInfo = true,
		UiMapLayerInfo = true,
		UnitAuraUpdateInfo = true,
		UnitPowerBarInfo = true,
		UnitPowerBarWidgetVisualizationInfo = true,
		UnlockedAzeriteEmpoweredItems = true,
		VignetteInfo = true,
		VoiceAudioDevice = true,
		VoiceChatChannel = true,
		VoiceChatMember = true,
		VoiceChatProcess = true,
		VoiceTtsVoiceType = true,
		WeeklyRewardActivityEncounterInfo = true,
		WeeklyRewardActivityInfo = true,
		WeeklyRewardActivityRewardInfo = true,
		WhoInfo = true,
		WowLocale = true,
		XMLTemplateInfo = true,
		XMLTemplateKeyValue = true,
		XMLTemplateListInfo = true,
		ZoneAbilityInfo = true,
		ZoneControlVisualizationInfo = true,
		ZoneEntry = true,
	},
}

data.blizzardTypes = {}
for _, v in pairs(BlizardTypes) do
	data.blizzardTypes[v.Name] = v
end

return data
