-- names prefixed with # will not be hyperlinks
-- names prefixed with @ will have `?redirect=no`
local data = {
	-- groups
	{"C_BattleNet.GetFriendAccountInfo", "#C_BattleNet.GetAccountInfoByID", "#C_BattleNet.GetAccountInfoByGUID", "BNGetFriendInfo", "#BNGetFriendInfoByID"},
	{"C_BattleNet.GetFriendGameAccountInfo", "#C_BattleNet.GetGameAccountInfoByID", "#C_BattleNet.GetGameAccountInfoByGUID", "BNGetFriendGameAccountInfo", "#BNGetGameAccountInfo", "#BNGetGameAccountInfoByGUID", "#BNGetFriendToonInfo", "#BNGetToonInfo"},
	{"C_ChatInfo.SendAddonMessage", "#C_ChatInfo.SendAddonMessageLogged", "#SendAddonMessage"},
	{"C_CreatureInfo.GetClassInfo", "GetClassInfo"},
	{"C_PartyInfo.InviteUnit", "InviteUnit", "#InviteByName"},
	{"C_PlayerChoice.GetCurrentPlayerChoiceInfo", "C_PlayerChoice.GetPlayerChoiceInfo", "C_PlayerChoice.GetPlayerChoiceOptionInfo", "C_PlayerChoice.GetPlayerChoiceRewardInfo", "#C_QuestChoice.GetQuestChoiceInfo", "#C_QuestChoice.GetQuestChoiceOptionInfo", "#GetQuestChoiceInfo", "#GetQuestChoiceOptionInfo", "#GetQuestChoiceRewardCurrency", "#GetQuestChoiceRewardFaction", "#GetQuestChoiceRewardInfo", "#GetQuestChoiceRewardItem"},
	{"C_ReportSystem.SendReport", "C_ReportSystem.OpenReportPlayerDialog", "C_ReportSystem.SendReportPlayer", "#C_ChatInfo.ReportPlayer"},
	{"C_TradeSkillUI.GetProfessionInfoBySkillLineID", "C_TradeSkillUI.GetTradeSkillLine", "C_TradeSkillUI.GetTradeSkillLineInfoByID", "GetTradeSkillLine", "GetCraftSkillLine"},
	{"EnableAddOn", "DisableAddOn"},
	{"GetHaste", "GetMeleeHaste", "GetRangedHaste"},
	{"GetMoney", "GetCoinText", --[["GetMoneyString",]] "GetCoinTextureString"},
	{"IsModifierKeyDown", "IsControlKeyDown", "IsShiftKeyDown", "IsAltKeyDown", "IsLeftControlKeyDown", "IsLeftShiftKeyDown", "IsLeftAltKeyDown", "IsRightControlKeyDown", "IsRightShiftKeyDown", "IsRightAltKeyDown"},
	{"SetPVP", "TogglePVP", "GetPVPDesired"},
	{"UnitAura", "#UnitBuff", "#UnitDebuff"},
	{"C_UnitAuras.GetPlayerAuraBySpellID", "GetPlayerAuraBySpellID"},
	{"C_UnitAuras.GetAuraDataBySlot", "UnitAuraBySlot"},

	-- variations of the same api
	{"C_ArtifactUI.GetPowersAffectedByRelic", "#C_ArtifactUI.GetPowersAffectedByRelicItemLink"},
	{"C_ArtifactUI.GetRelicInfo", "#C_ArtifactUI.GetRelicInfoByItemID"},
	{"C_AzeriteEmpoweredItem.GetAllTierInfo", "#C_AzeriteEmpoweredItem.GetAllTierInfoByItemID"},
	{"C_AzeriteEmpoweredItem.IsAzeriteEmpoweredItem", "#C_AzeriteEmpoweredItem.IsAzeriteEmpoweredItemByID"},
	{"C_AzeriteItem.IsAzeriteItem", "#C_AzeriteItem.IsAzeriteItemByID"},
	{"C_BlackMarket.GetItemInfoByID", "#C_BlackMarket.GetItemInfoByIndex", "#C_BlackMarket.GetHotItem"},
	{"C_Calendar.EventRemoveInvite", "#C_Calendar.EventRemoveInviteByGuid"},
	{"C_ChatInfo.GetChannelRuleset", "#C_ChatInfo.GetChannelRulesetForChannelID"},
	{"C_ChatInfo.GetChannelShortcut", "#C_ChatInfo.GetChannelShortcutForChannelID"},
	{"C_ChatInfo.IsChannelRegional", "#C_ChatInfo.IsChannelRegionalForChannelID"},
	{"C_ClubFinder.GetRecruitingClubInfoFromClubID", "C_ClubFinder.GetRecruitingClubInfoFromFinderGUID"},
	{"C_Commentator.GetTeamColor", "#C_Commentator.GetTeamColorByUnit", "C_Commentator.GetTeamHighlightColor"},
	{"C_EncounterJournal.GetLootInfo", "#C_EncounterJournal.GetLootInfoByIndex", "EJ_GetLootInfo"},
	{"C_FriendList.GetFriendInfo", "#C_FriendList.GetFriendInfoByIndex", "GetFriendInfo"},
	{"C_Item.DoesItemExist", "#C_Item.DoesItemExistByID"},
	{"C_Item.GetItemIcon", "#C_Item.GetItemIconByID"},
	{"C_Item.GetItemInventoryType", "#C_Item.GetItemInventoryTypeByID"},
	{"C_Item.GetItemName", "#C_Item.GetItemNameByID"},
	{"C_Item.GetItemQuality", "#C_Item.GetItemQualityByID"},
	{"C_Item.IsItemDataCached", "#C_Item.IsItemDataCachedByID"},
	{"C_Item.LockItem", "#C_Item.LockItemByGUID"},
	{"C_Item.RequestLoadItemData", "#C_Item.RequestLoadItemDataByID"},
	{"C_Item.UnlockItem", "#C_Item.UnlockItemByGUID"},
	{"C_Map.GetUserWaypoint", "#C_Map.GetUserWaypointFromHyperlink"},
	{"C_MountJournal.GetMountAllCreatureDisplayInfoByID", "#C_MountJournal.GetDisplayedMountAllCreatureDisplayInfo"},
	{"C_ReportSystem.SetPendingReportTarget", "#C_ReportSystem.SetPendingReportTargetByGuid"},
	{"C_Scenario.GetCriteriaInfo", "#C_Scenario.GetCriteriaInfoByStep"},
	{"C_Soulbinds.GetConduitCollectionData", "#C_Soulbinds.GetConduitCollectionDataAtCursor", "#C_Soulbinds.GetConduitCollectionDataByVirtualID"},
	{"C_Soulbinds.GetConduitRank", "#C_Soulbinds.GetConduitRankFromCollection"},
	{"C_TaskQuest.GetQuestTimeLeftSeconds", "#C_TaskQuest.GetQuestTimeLeftMinutes"},
	{"C_Timer.After", "C_Timer.NewTimer", "#C_Timer.NewTicker"},
	{"C_TransmogSets.SetHasNewSources", "C_TransmogSets.SetHasNewSourcesForSlot"},
	{"EJ_GetEncounterInfo", "#EJ_GetEncounterInfoByIndex"},
	{"GetAchievementCriteriaInfo", "#GetAchievementCriteriaInfoByID"},
	{"GetRealmName", "#GetNormalizedRealmName"},
	{"GetSpecializationInfo", "#GetSpecializationInfoByID", "#GetSpecializationInfoForClassID", "#GetSpecializationInfoForSpecID"},
	{"GetTalentInfo", "#GetTalentInfoByID", "#GetTalentInfoBySpecialization"},
	{"GetUnitPowerBarInfo", "#GetUnitPowerBarInfoByID"},
	{"GetUnitPowerBarStrings", "#GetUnitPowerBarStringsByID"},
	{"GetUnitPowerBarTextureInfo", "#GetUnitPowerBarTextureInfoByID"},
	{"securecall", "#securecallfunction"},
	{"strsplit", "#strsplittable"},
	{"UnitClass", "#UnitClassBase"},
	{"UnitName", "#UnitFullName", "#UnitNameUnmodified"},

	-- replacements, only exist on single flavor
	{"C_Calendar.EventGetInvite", "#CalendarEventGetInvite"},
	{"C_Calendar.OpenEvent", "#CalendarOpenEvent"},
	{"C_Calendar.GetEventInfo", "#CalendarGetEventInfo"},
	{"C_ChatInfo.SwapChatChannelsByChannelIndex", "#SwapChatChannelByLocalID"},
	{"C_Commentator.GetPlayerData", "C_Commentator.GetPlayerInfo"},
	{"C_Commentator.SetBlocklistedAuras", "#C_Commentator.SetBlacklistedAuras"},
	{"C_Commentator.SetBlocklistedCooldowns", "#C_Commentator.SetBlacklistedCooldowns"},
	{"C_DateAndTime.GetCurrentCalendarTime", "#C_Calendar.GetDate", "#CalendarGetDate"},
	{"C_DeathInfo.GetDeathReleasePosition", "GetDeathReleasePosition"},
	{"C_EncounterJournal.GetSlotFilter", "#EJ_GetSlotFilter"},
	{"C_EncounterJournal.ResetSlotFilter", "#EJ_ResetSlotFilter"},
	{"C_EncounterJournal.SetSlotFilter", "EJ_SetSlotFilter"},
	{"C_EquipmentSet.EquipmentSetContainsLockedItems", "#EquipmentSetContainsLockedItems"},
	{"C_EquipmentSet.GetEquipmentSetInfo", "#GetEquipmentSetInfo"},
	{"C_EquipmentSet.GetIgnoredSlots", "#GetEquipmentSetIgnoreSlots"},
	{"C_EquipmentSet.GetItemIDs", "#GetEquipmentSetItemIDs"},
	{"C_EquipmentSet.GetItemLocations", "#GetEquipmentSetLocations"},
	{"C_EquipmentSet.GetNumEquipmentSets", "#GetNumEquipmentSets"},
	{"C_EquipmentSet.IgnoreSlotForSave", "#EquipmentManagerIgnoreSlotForSave"},
	{"C_EquipmentSet.IsSlotIgnoredForSave", "#EquipmentManagerIsSlotIgnoredForSave"},
	{"C_EquipmentSet.ModifyEquipmentSet", "#ModifyEquipmentSet"},
	{"C_EquipmentSet.PickupEquipmentSet", "#PickupEquipmentSet"},
	{"C_EquipmentSet.SaveEquipmentSet", "#SaveEquipmentSet"},
	{"C_EquipmentSet.UnignoreSlotForSave", "#EquipmentManagerUnignoreSlotForSave"},
	{"C_EquipmentSet.UseEquipmentSet", "#UseEquipmentSet"},
	{"C_FriendList.AddOrRemoveFriend", "#AddOrRemoveFriend"},
	{"C_FriendList.GetWhoInfo", "@GetWhoInfo"},
	{"C_FriendList.GetNumWhoResults", "@GetNumWhoResults"},
	{"C_GossipInfo.GetPoiInfo", "#C_GossipInfo.GetGossipPoiInfo"},
	{"C_GuildInfo.QueryGuildMembersForRecipe", "#QueryGuildMembersForRecipe"},
	{"C_ItemUpgrade.ClearItemUpgrade", "#ClearItemUpgrade"},
	{"C_ItemUpgrade.CloseItemUpgrade", "#CloseItemUpgrade"},
	{"C_ItemUpgrade.GetItemUpgradeCurrentLevel", "GetItemUpdateLevel"},
	{"C_ItemUpgrade.GetItemUpgradeEffect", "#GetItemUpgradeEffect"},
	{"C_ItemUpgrade.GetItemUpgradeItemInfo", "C_ItemUpgrade.GetItemLevelIncrement", "#GetItemLevelIncrement", "GetItemUpgradeItemInfo", "#GetItemUpgradeStats"},
	{"C_ItemUpgrade.GetNumItemUpgradeEffects", "#GetNumItemUpgradeEffects"},
	{"C_ItemUpgrade.SetItemUpgradeFromCursorItem", "#SetItemUpgradeFromCursorItem"},
	{"C_ItemUpgrade.UpgradeItem", "#UpgradeItem"},
	{"C_LegendaryCrafting.GetRuneforgePowersByClassSpecAndCovenant", "#C_LegendaryCrafting.GetRuneforgePowersByClassAndSpec"},
	{"C_LossOfControl.GetActiveLossOfControlData", "C_LossOfControl.GetActiveLossOfControlDataByUnit", "C_LossOfControl.GetEventInfo"},
	{"C_LossOfControl.GetActiveLossOfControlDataCount", "C_LossOfControl.GetActiveLossOfControlDataCountByUnit", "C_LossOfControl.GetNumEvents"},
	{"C_Map.GetMapInfo", "#GetMapInfo", "GetMapNameByID"},
	{"C_MountJournal.GetMountInfoByID", "#C_MountJournal.GetDisplayedMountInfo", "C_MountJournal.GetMountInfo"},
	{"C_MountJournal.GetMountInfoExtraByID", "#C_MountJournal.GetDisplayedMountInfoExtra", "C_MountJournal.GetMountInfoExtra"},
	{"C_PlayerChoice.SendPlayerChoiceResponse", "#SendPlayerChoiceResponse", "#SendQuestChoiceResponse"},
	{"C_PlayerInfo.CanPlayerUseMountEquipment", "#C_MountJournal.IsMountEquipmentUnlocked"},
	{"C_PlayerInfo.GetAlternateFormInfo", "#HasAlternateForm"},
	{"C_PlayerMentorship.GetMentorRequirements", "C_PlayerMentorship.GetMentorOptionalAchievementIDs"},
	{"C_PvP.GetArenaRewards", "#GetArenaRewards"},
	{"C_PvP.GetArenaSkirmishRewards", "#GetArenaSkirmishRewards"},
	{"C_PvP.GetAvailableBrawlInfo", "#C_PvP.GetBrawlInfo"},
	{"C_PvP.GetRandomBGRewards", "#GetRandomBGRewards"},
	{"C_PvP.GetRatedBGRewards", "#GetRatedBGRewards"},
	{"C_PvP.GetScoreInfo", "#C_PvP.GetScoreInfoByPlayerGuid"},
	{"C_PvP.GetSpecialEventBrawlInfo", "C_PvP.GetSpecialEventDetails", "C_PvP.GetSpecialEventInfo"},
	{"C_QuestLog.AddWorldQuestWatch", "#AddWorldQuestWatch"},
	{"C_QuestLog.GetDistanceSqToQuest", "#C_TaskQuest.GetDistanceSqToQuest", "#GetDistanceSqToQuest"},
	{"C_QuestLog.GetQuestLogPortraitGiver", "#GetQuestLogPortraitGiver"},
	{"C_QuestLog.IsQuestTask", "IsQuestTask"},
	{"C_QuestLog.RemoveWorldQuestWatch", "#RemoveWorldQuestWatch"},
	{"C_SocialRestrictions.AcknowledgeRegionalChatDisabled", "#AcknowledgeAADCAlert"},
	{"C_SpellBook.GetCurrentLevelSpells", "GetCurrentLevelSpells"},
	{"C_TaxiMap.GetAllTaxiNodes", "#GetAllTaxiNodes"},
	{"C_Transmog.CanTransmogItem", "C_Transmog.GetItemInfo", "#GetItemTransmogrifyInfo"},
	{"C_Transmog.GetApplyCost", "C_Transmog.GetCost", "#GetTransmogrifyCost"},
	{"C_Transmog.GetSlotInfo", "#GetTransmogrifySlotInfo"},
	{"C_TransmogCollection.GetFallbackWeaponAppearance", "#C_TransmogCollection.GetIllusionFallbackWeaponSource"},
	{"C_TransmogCollection.GetOutfitInfo", "C_TransmogCollection.GetOutfitName"},
	{"C_TransmogSets.GetSetPrimaryAppearances", "C_TransmogSets.GetSetSources"},
	{"GetGuildTabardFiles", "GetGuildTabardFileNames"},
	{"GetPvpTalentInfoByID", "#GetPvpTalentInfo"},
	{"SaveBindings", "#AttemptToSaveBindings"},
	{"SetupFullscreenScale", "#SetupWorldMapScale"},
	{"StartDuel", "#StartDuelUnit"},
	{"C_ReportSystem.CanReportPlayer", "C_ChatInfo.CanReportPlayer"},
	{"C_ReportSystem.ReportServerLag", "C_ChatInfo.ReportServerLag"},

	-- replacements, across multiple flavors
	{"C_AuctionHouse.GetAuctionItemSubClasses", "GetAuctionItemSubClasses"},
	{"C_AuctionHouse.GetNumReplicateItems", "GetNumAuctionItems"},
	{"C_AuctionHouse.GetReplicateItemBattlePetInfo", "GetAuctionItemBattlePetInfo"},
	{"C_AuctionHouse.GetReplicateItemInfo", "GetAuctionItemInfo"},
	{"C_AuctionHouse.GetReplicateItemLink", "GetAuctionItemLink"},
	{"C_AuctionHouse.GetReplicateItemTimeLeft", "GetAuctionItemTimeLeft"},
	{"C_AuctionHouse.ReplicateItems", "QueryAuctionItems"},
	{"C_Calendar.GetGuildEventInfo", "GetGuildEventInfo"},
	{"C_CurrencyInfo.ExpandCurrencyList", "ExpandCurrencyList"},
	{"C_CurrencyInfo.GetBackpackCurrencyInfo", "GetBackpackCurrencyInfo"},
	{"C_CurrencyInfo.GetCurrencyInfo", "#C_CurrencyInfo.GetCurrencyInfoFromLink", "GetCurrencyInfo"},
	{"C_CurrencyInfo.GetCurrencyLink", "GetCurrencyLink"},
	{"C_CurrencyInfo.GetCurrencyListInfo", "GetCurrencyListInfo"},
	{"C_CurrencyInfo.GetCurrencyListLink", "GetCurrencyListLink"},
	{"C_CurrencyInfo.GetCurrencyListSize", "GetCurrencyListSize"},
	{"C_CurrencyInfo.SetCurrencyBackpack", "SetCurrencyBackpack"},
	{"C_CurrencyInfo.SetCurrencyUnused", "SetCurrencyUnused"},
	{"C_EquipmentSet.CanUseEquipmentSets", "#CanUseEquipmentSets"},
	{"C_EquipmentSet.ClearIgnoredSlotsForSave", "#EquipmentManagerClearIgnoredSlotsForSave"},
	{"C_EquipmentSet.DeleteEquipmentSet", "#DeleteEquipmentSet"},
	{"C_GossipInfo.CloseGossip", "CloseGossip"},
	{"C_GossipInfo.ForceGossip", "ForceGossip"},
	{"C_GossipInfo.GetActiveQuests", "GetGossipActiveQuests"},
	{"C_GossipInfo.GetAvailableQuests", "GetGossipAvailableQuests"},
	{"C_GossipInfo.GetNumActiveQuests", "GetNumGossipActiveQuests"},
	{"C_GossipInfo.GetNumAvailableQuests", "GetNumGossipAvailableQuests"},
	{"C_GossipInfo.GetNumOptions", "GetNumGossipOptions"},
	{"C_GossipInfo.GetOptions", "GetGossipOptions"},
	{"C_GossipInfo.GetPoiForUiMapID", "C_GossipInfo.GetGossipPoiForUiMapID"},
	{"C_GossipInfo.GetText", "GetGossipText"},
	{"C_GossipInfo.SelectActiveQuest", "SelectGossipActiveQuest"},
	{"C_GossipInfo.SelectAvailableQuest", "SelectGossipAvailableQuest"},
	{"C_GossipInfo.SelectOption", "C_GossipInfo.SelectOptionByIndex", "SelectGossipOption"},
	{"C_GuildInfo.GuildRoster", "GuildRoster"},
	{"C_GuildInfo.IsGuildRankAssignmentAllowed", "#IsGuildRankAssignmentAllowed"},
	{"C_Item.IsDressableItemByID", "IsDressableItem"},
	{"C_LFGInfo.GetDungeonInfo", "GetDungeonInfo"},
	{"C_LFGList.GetActivityInfoTable", "C_LFGList.GetActivityInfo"},
	{"C_LFGList.GetLfgCategoryInfo", "C_LFGList.GetCategoryInfo"},
	{"C_PartyInfo.ConvertToParty", "ConvertToParty"},
	{"C_PartyInfo.LeaveParty", "LeaveParty"},
	{"C_PvP.GetBattlefieldFlagPosition", "GetBattlefieldFlagPosition"},
	{"C_PvP.GetMatchPVPStatColumn", "GetBattlefieldStatInfo"},
	{"C_PvP.GetMatchPVPStatColumns", "C_PvP.GetMatchPVPStatIDs", "GetNumBattlefieldStats"},
	{"C_PvP.IsActiveBattlefield", "InActiveBattlefield"},
	{"C_QuestLog.AbandonQuest", "AbandonQuest"},
	{"C_QuestLog.AddQuestWatch", "#AddQuestWatchForQuestID", "AddQuestWatch"},
	{"C_QuestLog.CanAbandonQuest", "CanAbandonQuest"},
	{"C_QuestLog.GetAbandonQuest", "GetAbandonQuestName"},
	{"C_QuestLog.GetAllCompletedQuestIDs", "GetQuestsCompleted"},
	{"C_QuestLog.GetInfo", "GetQuestLogTitle"},
	{"C_QuestLog.GetLogIndexForQuestID", "GetQuestLogIndexByID"},
	{"C_QuestLog.GetNumQuestLogEntries", "GetNumQuestLogEntries"},
	{"C_QuestLog.GetNumQuestWatches", "GetNumQuestWatches"},
	{"C_QuestLog.GetQuestTagInfo", "GetQuestTagInfo"},
	{"C_QuestLog.GetSelectedQuest", "GetQuestLogSelection"},
	{"C_QuestLog.GetSuggestedGroupSize", "GetQuestLogGroupNum"},
	{"C_QuestLog.GetTimeAllowed", "GetQuestTimers"},
	{"C_QuestLog.GetTitleForQuestID", "C_QuestLog.GetQuestInfo"},
	{"C_QuestLog.IsComplete", "IsQuestComplete"},
	{"C_QuestLog.IsPushableQuest", "GetQuestLogPushable"},
	{"C_QuestLog.IsQuestFlaggedCompleted", "IsQuestFlaggedCompleted"},
	{"C_QuestLog.IsUnitOnQuest", "IsUnitOnQuest"},
	{"C_QuestLog.RemoveQuestWatch", "#RemoveQuestWatchForQuestID", "RemoveQuestWatch"},
	{"C_QuestLog.SetAbandonQuest", "SetAbandonQuest"},
	{"C_QuestLog.SetSelectedQuest", "SelectQuestLogEntry"},
	{"C_QuestLog.SortQuestWatches", "SortQuestWatches"},
	{"C_TradeSkillUI.CloseTradeSkill", "CloseTradeSkill"},
	{"C_TradeSkillUI.CraftRecipe", "DoTradeSkill"},
	{"C_TradeSkillUI.GetRecipeDescription", "GetTradeSkillDescription", "GetCraftDescription"},
	{"C_TradeSkillUI.GetRecipeInfo", "GetTradeSkillInfo", "GetCraftInfo"},
	{"C_TradeSkillUI.GetRecipeItemLink", "GetTradeSkillItemLink"},
	{"C_TradeSkillUI.GetRecipeLink", "GetTradeSkillRecipeLink", "GetCraftRecipeLink"},
	{"C_TradeSkillUI.GetRecipeNumItemsProduced", "GetTradeSkillNumMade"},
	{"C_TradeSkillUI.GetRecipeSchematic", "C_TradeSkillUI.GetRecipeNumReagents", "GetTradeSkillNumReagents"},
	{"C_TradeSkillUI.GetRecipeSchematic", "C_TradeSkillUI.GetRecipeReagentInfo", "GetTradeSkillReagentInfo"},
	{"C_TradeSkillUI.GetRecipeReagentItemLink", "GetTradeSkillReagentItemLink"},
	{"C_TradeSkillUI.GetRemainingRecasts", "C_TradeSkillUI.GetRecipeRepeatCount", "GetTradeskillRepeatCount"},
	{"C_TradeSkillUI.GetRecipeTools", "GetTradeSkillTools"},
	{"C_TradeSkillUI.GetTradeSkillListLink", "GetTradeSkillListLink"},
	{"GetExpertise", "GetExpertisePercent"},
	{"GetNumSpecializations", "GetNumTalentTabs"},
	{"GetNumTradeSkills", "GetNumCrafts"},
	{"GetPersonalRatedInfo", "GetArenaTeamRosterInfo"},
	{"SetTracking", "CancelTrackingBuff"},
	{"UnitPhaseReason", "UnitIsWarModePhased", "UnitInPhase"},
	{"UnitQuestTrivialLevelRange", "GetQuestGreenRange"},
	{"GetActiveSpecGroup", "GetActiveTalentGroup"},
	{"C_PetJournal.GetPetCooldownByGUID", "GetCompanionCooldown"},
	{"C_TradeSkillUI.IsTradeSkillLinked", "IsTradeSkillLinked"},
	{"C_CurrencyInfo.PickupCurrency", "PickupCurrency"},
	{"C_PartyInfo.RequestInviteFromUnit", "RequestInviteFromUnit"},
	{"C_AreaPoiInfo.GetAreaPOISecondsLeft", "C_AreaPoiInfo.GetAreaPOITimeLeft"},
	{"C_QuestLog.GetBountySetInfoForMapID", "C_Map.GetBountySetIDForMap", "#GetQuestBountyInfoForMapID"},
	{"GetNumUnspentTalents", "GetUnspentTalentPoints"},
	{"SetSpecialization", "SetActiveTalentGroup"},
	{"C_TradeSkillUI.StopRecipeRepeat", "StopTradeSkillRepeat"},
	{"C_MountJournal.SummonByID", "C_MountJournal.Summon"},

	-- 10.0.0
	{"_Minimap.GetPOITextureCoords", "GetPOITextureCoords"},
	{"C_GossipInfo.GetFriendshipReputation", "GetFriendshipReputation"},
	{"C_GossipInfo.GetFriendshipReputationRanks", "GetFriendshipReputationRanks"},
	{"C_Minimap.CanTrackBattlePets", "CanTrackBattlePets"},
	{"C_Minimap.ClearAllTracking", "ClearAllTracking"},
	{"C_Minimap.GetNumQuestPOIWorldEffects", "GetNumQuestPOIWorldEffects"},
	{"C_Minimap.GetNumTrackingTypes", "GetNumTrackingTypes"},
	{"C_Minimap.GetObjectIconTextureCoords", "GetObjectIconTextureCoords"},
	{"C_Minimap.GetTrackingInfo", "GetTrackingInfo"},
	{"C_Minimap.IsTrackingBattlePets", "IsTrackingBattlePets"},
	{"C_Minimap.IsTrackingHiddenQuests", "IsTrackingHiddenQuests"},
	{"C_Minimap.SetTracking", "SetTracking"},
	{"C_PlayerInteractionManager.InteractUnit", "InteractUnit"},
	{"C_PlayerInteractionManager.IsReplacingUnit", "IsReplacingUnit"},
	{"C_PlayerInteractionManager.ReopenInteraction", "ReopenInteraction"},
	{"C_TradeSkillUI.GetCraftingReagentBonusText", "C_TradeSkillUI.GetOptionalReagentBonusText"},
	{"C_UnitAuras.GetPlayerAuraBySpellID", "GetPlayerAuraBySpellID"},
	{"IsPlayerInGuildFromGUID", "C_PlayerInfo.IsPlayerInGuildFromGUID"},
	{"C_Container.ContainerIDToInventoryID", "ContainerIDToInventoryID"},
	{"C_Container.ContainerRefundItemPurchase", "ContainerRefundItemPurchase"},
	{"C_Container.GetBackpackAutosortDisabled", "GetBackpackAutosortDisabled"},
	{"C_Container.GetBagName", "GetBagName"},
	{"C_Container.GetBagSlotFlag", "GetBagSlotFlag"},
	{"C_Container.GetBankAutosortDisabled", "GetBankAutosortDisabled"},
	{"C_Container.GetContainerFreeSlots", "GetContainerFreeSlots"},
	{"C_Container.GetContainerItemCooldown", "GetContainerItemCooldown"},
	{"C_Container.GetContainerItemDurability", "GetContainerItemDurability"},
	{"C_Container.GetContainerItemEquipmentSetInfo", "GetContainerItemEquipmentSetInfo"},
	{"C_Container.GetContainerItemID", "GetContainerItemID"},
	{"C_Container.GetContainerItemInfo", "GetContainerItemInfo"},
	{"C_Container.GetContainerItemLink", "GetContainerItemLink"},
	{"C_Container.GetContainerItemPurchaseCurrency", "GetContainerItemPurchaseCurrency"},
	{"C_Container.GetContainerItemPurchaseInfo", "GetContainerItemPurchaseInfo"},
	{"C_Container.GetContainerItemPurchaseItem", "GetContainerItemPurchaseItem"},
	{"C_Container.GetContainerItemQuestInfo", "GetContainerItemQuestInfo"},
	{"C_Container.GetContainerNumFreeSlots", "GetContainerNumFreeSlots"},
	{"C_Container.GetContainerNumSlots", "GetContainerNumSlots"},
	{"C_Container.GetInsertItemsLeftToRight", "GetInsertItemsLeftToRight"},
	{"C_Container.GetItemCooldown", "GetItemCooldown"},
	{"C_Container.GetMaxArenaCurrency", "GetMaxArenaCurrency"},
	{"C_Container.GetSortBagsRightToLeft", "GetSortBagsRightToLeft"},
	{"C_Container.IsBattlePayItem", "IsBattlePayItem"},
	{"C_Container.IsContainerFiltered", "IsContainerFiltered"},
	{"C_Container.PickupContainerItem", "PickupContainerItem"},
	{"C_Container.PlayerHasHearthstone", "PlayerHasHearthstone"},
	{"C_Container.SetBackpackAutosortDisabled", "SetBackpackAutosortDisabled"},
	{"C_Container.SetBagPortraitTexture", "SetBagPortraitTexture", "SetBagPortaitTexture"},
	{"C_Container.SetBagSlotFlag", "SetBagSlotFlag"},
	{"C_Container.SetBankAutosortDisabled", "SetBankAutosortDisabled"},
	{"C_Container.SetInsertItemsLeftToRight", "SetInsertItemsLeftToRight"},
	{"C_Container.SetItemSearch", "SetItemSearch"},
	{"C_Container.SetSortBagsRightToLeft", "SetSortBagsRightToLeft"},
	{"C_Container.ShowContainerSellCursor", "ShowContainerSellCursor"},
	{"C_Container.SocketContainerItem", "SocketContainerItem"},
	{"C_Container.SortBags", "SortBags"},
	{"C_Container.SortBankBags", "SortBankBags"},
	{"C_Container.SortReagentBankBags", "SortReagentBankBags"},
	{"C_Container.SplitContainerItem", "SplitContainerItem"},
	{"C_Container.UseContainerItem", "UseContainerItem"},
	{"C_Container.UseHearthstone", "UseHearthstone"},
	{"C_PaperDollInfo.CanCursorCanGoInSlot", "CursorCanGoInSlot"},
	
	-- 10.1.0
	{"C_AddOns.GetAddOnMetadata", "GetAddOnMetadata"},
	{"C_QuestInfoSystem.GetQuestRewardSpellInfo", "GetQuestLogRewardSpell"},

	-- 10.1.5
	{"C_ContentTracking.StartTracking", "AddTrackedAchievement"},
	{"C_ContentTracking.StopTracking", "RemoveTrackedAchievement"},

	-- 10.1.7
	{"C_SpecializationInfo.GetClassIDFromSpecID", "GetClassIDFromSpecID"},

	-- FrameScriptObject
	{"FrameScriptObject GetObjectType", "FrameScriptObject IsObjectType"},
	{"FrameScriptObject IsForbidden", "FrameScriptObject SetForbidden", "ScriptRegion IsProtected"},
	{"FrameScriptObject GetName", "Object GetDebugName"},
	-- Object
	{"Object GetParent", "ScriptRegion SetParent", "Frame GetChildren"},
	{"Object GetParentKey", "Object SetParentKey"},
	-- ScriptRegion
	{"ScriptRegion EnableMouse", "ScriptRegion IsMouseEnabled"},
	{"ScriptRegion SetMouseMotionEnabled", "ScriptRegion EnableMouseMotion", "ScriptRegion IsMouseMotionEnabled", "ScriptRegion IsMouseOver", "ScriptRegion IsMouseMotionFocus", "UIHANDLER OnEnter", "UIHANDLER OnLeave"},
	{"ScriptRegion SetMouseClickEnabled", "ScriptRegion IsMouseClickEnabled"},
	{"UIHANDLER OnMouseDown", "UIHANDLER OnMouseUp"},
	{"ScriptRegion GetLeft", "#ScriptRegion GetRight", "#ScriptRegion GetBottom", "#ScriptRegion GetTop", "#ScriptRegion GetCenter"},
	{"ScriptRegion GetRect", "#ScriptRegion GetScaledRect", "ScriptRegion IsRectValid"},
	{"ScriptRegion GetSize", "#ScriptRegion GetWidth", "#ScriptRegion GetHeight", "ScriptRegionResizing SetSize", "#ScriptRegionResizing SetWidth", "#ScriptRegionResizing SetHeight"},
	{"ScriptRegion EnableMouseWheel", "ScriptRegion IsMouseWheelEnabled", "UIHANDLER OnMouseWheel"},
	{"ScriptRegion GetScript", "ScriptRegion SetScript", "ScriptRegion HasScript", "ScriptRegion HookScript"},
	{"ScriptRegion Show", "ScriptRegion Hide", "ScriptRegion SetShown", "ScriptRegion IsShown", "#ScriptRegion IsVisible", "UIHANDLER OnShow", "UIHANDLER OnHide"},
	{"ScriptRegionResizing GetPoint", "ScriptRegionResizing GetPointByName", "ScriptRegionResizing GetNumPoints", "ScriptRegionResizing SetPoint", "ScriptRegionResizing SetAllPoints", "ScriptRegionResizing ClearPoint", "ScriptRegionResizing ClearAllPoints"},
	{"ScriptRegionResizing AdjustPointsOffset", "ScriptRegionResizing ClearPointsOffset"},
	{"AnimatableObject CreateAnimationGroup", "AnimatableObject GetAnimationGroups", "AnimatableObject StopAnimating"},
	{"Frame RegisterForDrag", "ScriptRegion IsDragging", "UIHANDLER OnDragStart", "UIHANDLER OnDragStop", "UIHANDLER OnReceiveDrag"},
	-- Region
	{"Region GetAlpha", "#Frame GetEffectiveAlpha", "Region SetAlpha", "Region SetIgnoreParentAlpha", "Region IsIgnoringParentAlpha"},
	{"Region GetScale", "#Region GetEffectiveScale", "Region SetScale", "Region SetIgnoreParentScale", "Region IsIgnoringParentScale"},
	{"Region GetVertexColor", "Region SetVertexColor"},
	{"Region GetDrawLayer", "Region SetDrawLayer"},
	-- TextureBase
	{"TextureBase GetAtlas", "TextureBase SetAtlas"},
	{"TextureBase GetBlendMode", "TextureBase SetBlendMode"},
	{"TextureBase IsDesaturated", "TextureBase SetDesaturated", "TextureBase GetDesaturation", "TextureBase SetDesaturation"},
	{"TextureBase GetHorizTile", "TextureBase GetVertTile", "TextureBase SetHorizTile", "TextureBase SetVertTile"},
	{"TextureBase GetRotation", "TextureBase SetRotation"},
	{"TextureBase GetTexCoord", "TextureBase SetTexCoord"},
	{"TextureBase GetTexelSnappingBias", "TextureBase SetTexelSnappingBias", "TextureBase IsSnappingToPixelGrid", "TextureBase SetSnapToPixelGrid"},
	{"TextureBase GetTexture", "TextureBase GetTextureFileID", "TextureBase GetTextureFilePath", "TextureBase SetTexture",  "TextureBase SetColorTexture"},
	{"TextureBase GetVertexOffset", "TextureBase SetVertexOffset"},
	{"TextureBase IsBlockingLoadRequested", "TextureBase SetBlockingLoadsRequested"},
	-- Texture
	{"Texture GetNumMaskTextures", "Texture GetMaskTexture", "Texture AddMaskTexture", "Texture RemoveMaskTexture"},
	-- Line
	{"Line GetStartPoint", "Line SetStartPoint"},
	{"Line GetEndPoint", "Line SetEndPoint"},
	{"Line GetThickness", "Line SetThickness"},
	{"Line GetAlpha", "Line SetAlpha"},
	{"Line GetFont", "Line SetFont"},
	{"Line GetFontObject", "Line SetFontObject"},
	{"Line GetIndentedWordWrap", "Line SetIndentedWordWrap"},
	{"Line GetJustifyH", "Line GetJustifyV", "Line SetJustifyH", "Line SetJustifyV"},
	{"Line GetShadowColor", "Line SetShadowColor"},
	{"Line GetShadowOffset", "Line SetShadowOffset"},
	{"Line GetSpacing", "Line SetSpacing"},
	{"Line GetTextColor", "Line SetTextColor"},

	{"FontString CanNonSpaceWrap", "FontString SetNonSpaceWrap"},
	{"FontString CanWordWrap", "FontString SetWordWrap"},
	{"FontString GetFont", "FontString SetFont"},
	{"FontString GetFontObject", "FontString SetFontObject"},
	{"FontString GetIndentedWordWrap", "FontString SetIndentedWordWrap"},
	{"FontString GetJustifyH", "FontString GetJustifyV", "FontString SetJustifyH", "FontString SetJustifyV"},
	{"FontString GetMaxLines", "FontString SetMaxLines"},
	{"FontString GetRotation", "FontString SetRotation"},
	{"FontString GetShadowColor", "FontString SetShadowColor"},
	{"FontString GetShadowOffset", "FontString SetShadowOffset"},
	{"FontString GetSpacing", "FontString SetSpacing"},
	{"FontString GetStringWidth", "FontString GetStringHeight"},
	{"FontString GetText", "FontString SetText", "FontString SetFormattedText"},
	{"FontString GetTextColor", "FontString SetTextColor"},
	{"FontString GetTextScale", "FontString SetTextScale"},

	-- Frame
	{"Frame GetClampRectInsets", "Frame SetClampRectInsets", "Frame IsClampedToScreen", "Frame SetClampedToScreen"},
	{"Frame EnableDrawLayer", "Frame DisableDrawLayer", "Frame SetDrawLayerEnabled"},
	{"Frame GetFlattensRenderLayers", "#Frame GetEffectivelyFlattensRenderLayers", "Frame SetFlattensRenderLayers"},
	{"Frame GetFrameLevel", "Frame SetFrameLevel", "Frame Lower", "Frame Raise", "Frame HasFixedFrameLevel", "Frame SetFixedFrameLevel"},
	{"Frame GetFrameStrata", "Frame SetFrameStrata", "Frame HasFixedFrameStrata", "Frame SetFixedFrameStrata"},
	{"Frame IsResizable", "Frame SetResizable", "Frame GetResizeBounds", "Frame SetResizeBounds", "Frame StartSizing"},
	{"Frame EnableKeyboard", "UIHANDLER OnKeyUp", "UIHANDLER OnKeyDown"},
	{"Frame GetAttribute", "Frame SetAttribute", "#Frame SetAttributeNoHandler", "Frame CanChangeAttribute", "Frame ExecuteAttribute", "UIHANDLER OnAttributeChanged"},
	{"Frame GetID", "Frame SetID"},
	{"Frame GetChildren", "Frame GetNumChildren"},
	{"Frame GetRegions", "Frame GetNumRegions"},
	{"Frame IsMovable", "Frame SetMovable", "Frame StartMoving"},
	{"Frame GetHitRectInsets", "Frame SetHitRectInsets"},
	{"Frame GetPropagateKeyboardInput", "Frame SetPropagateKeyboardInput"},
	{"Frame GetHyperlinksEnabled", "Frame SetHyperlinksEnabled", "UIHANDLER OnHyperlinkClick", "UIHANDLER OnHyperlinkEnter", "UIHANDLER OnHyperlinkLeave"},
	{"Frame RegisterEvent", "Frame RegisterUnitEvent", "Frame RegisterAllEvents", "Frame UnregisterEvent", "Frame UnregisterAllEvents", "Frame IsEventRegistered"},
	{"Frame IsGamePadButtonEnabled", "Frame EnableGamePadButton", "UIHANDLER OnGamePadButtonDown", "UIHANDLER OnGamePadButtonUp"},
	{"Frame IsGamePadStickEnabled", "Frame EnableGamePadStick", "UIHANDLER OnGamePadStick"},
	{"Frame IsToplevel", "Frame SetToplevel"},
	{"Frame IsUserPlaced", "Frame SetUserPlaced"},

	-- Button
	{"Button GetDisabledTexture", "Button SetDisabledTexture", "Button ClearDisabledTexture"},	
	{"Button GetHighlightTexture", "Button SetHighlightTexture", "Button ClearHighlightTexture"},	
	{"Button GetNormalTexture", "Button SetNormalTexture", "Button ClearNormalTexture"},	
	{"Button GetPushedTexture", "Button SetPushedTexture", "Button ClearPushedTexture"},	
	{"Button Enable", "Button Disable", "Button IsEnabled", "Button SetEnabled"},	
	{"Button GetButtonState", "Button SetButtonState"},	
	{"Button GetDisabledFontObject", "Button SetDisabledFontObject"},	
	{"Button GetDisabledTexture", "Button SetDisabledTexture"},	
	{"Button GetFontString", "Button SetFontString"},	
	{"Button GetHighlightFontObject", "Button SetHighlightFontObject"},	
	{"Button GetHighlightTexture", "Button SetHighlightTexture"},	
	{"Button GetMotionScriptsWhileDisabled", "Button SetMotionScriptsWhileDisabled"},	
	{"Button GetNormalFontObject", "Button SetNormalFontObject"},	
	{"Button GetPushedTextOffset", "Button SetPushedTextOffset"},	
	{"Button SetNormalAtlas", "Button SetHighlightAtlas", "Button SetPushedAtlas", "Button SetDisabledAtlas"},	
	{"Button GetTextHeight", "Button GetTextWidth"},	
	{"Button GetText", "Button SetText", "Button SetFormattedText"},	
	{"Button LockHighlight", "Button UnlockHighlight", "Button SetHighlightLocked"},	
	
	-- Button
	{"CheckButton GetChecked", "CheckButton SetChecked"},	
	{"CheckButton GetCheckedTexture", "CheckButton SetCheckedTexture"},	
	{"CheckButton GetDisabledCheckedTexture", "CheckButton SetDisabledCheckedTexture"},	

	-- Model
	{"Model GetFacing", "Model SetFacing"},
	{"Model SetFogColor", "Model SetFogFar", "Model SetFogNear"},
	
	-- ColorSelect
	{"ColorSelect GetColorHSV", "ColorSelect SetColorHSV"},
	{"ColorSelect GetColorRGB", "ColorSelect SetColorRGB"},
	{"ColorSelect GetColorValueTexture", "ColorSelect SetColorValueTexture"},
	{"ColorSelect GetColorValueThumbTexture", "ColorSelect SetColorValueThumbTexture"},
	{"ColorSelect GetColorWheelTexture", "ColorSelect SetColorWheelTexture", "ColorSelect ClearColorWheelTexture"},
	{"ColorSelect GetColorWheelThumbTexture", "ColorSelect SetColorWheelThumbTexture"},

	-- events
	-- {"COMBAT_LOG_EVENT", "#COMBAT_LOG_EVENT_UNFILTERED"},
	-- {"UNIT_HEALTH", "UNIT_HEALTH_FREQUENT"},
	-- {"SUPER_TRACKING_CHANGED", "SUPER_TRACKED_QUEST_CHANGED"},
	-- {"CURSOR_CHANGED", "CURSOR_UPDATE"},
}

return data
